// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Movie_DB.Models;

namespace Movie_DB.Migrations
{
    [DbContext(typeof(MoviesContext))]
    [Migration("20220127054717_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.13");

            modelBuilder.Entity("Movie_DB.Models.Movie", b =>
                {
                    b.Property<int>("MovieID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Category")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Director")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Edited")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LentTo")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<int>("Rating")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<short>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("MovieID");

                    b.ToTable("movies");

                    b.HasData(
                        new
                        {
                            MovieID = 1,
                            Category = 0,
                            Director = "Peter Jackson",
                            Edited = false,
                            Rating = 2,
                            Title = "The Lord of the Rings: Fellowship of the Ring",
                            Year = (short)2001
                        },
                        new
                        {
                            MovieID = 2,
                            Category = 0,
                            Director = "Christopher Nolan",
                            Edited = false,
                            Rating = 2,
                            Title = "Batman: The Dark Knight",
                            Year = (short)2008
                        },
                        new
                        {
                            MovieID = 3,
                            Category = 3,
                            Director = "Chris Sanders",
                            Edited = false,
                            Rating = 1,
                            Title = "How to Train Your Dragon",
                            Year = (short)2010
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
